### ISSUE TITLE
Guidance on how to use it on Teamcity

### ISSUE THREAD

**Issue by di97mni** [slvnperron/NUnit-retry#13]
We are using Teamcity and run Selenium tests after a successful build. The tests are failing randomly and we have tried to fix them but no luck. We will now try with NUnit-retry.

Any guidance how to setup that step on TC? I can see that there is a project named `TeamCity.NUnit.TestRunner.Proxy`

**Comment by slvnperron** [comment]
Yes. Here's the step we are using on the CI

Step 1: _NuGet Install_
Runner type: _NuGet Installer_ (Installs and updates missing NuGet packages)
Execute:
http://confluence.jetbrains.com/display/TCD8/Configuring+Build+Steps _If
all previous steps finished successfully (zero exit code)_
Path to NuGet.exe: _NuGet (version default (2.7.3))_
Package Sources: _Use nuget default package source_
Path to .sln: _src/NUnit-retry.sln_
Exclude Version: _OFF_
Restore Mode: _Install missing packages_
Use local machine packages cache: _OFF_
Update packages: _OFF_
Update mode: _Update via solution file_
Use safe packages update: _OFF_
Include PreRelease packages: _OFF_
Step 2: _Build_
Runner type: _Visual Studio (sln)_ (Microsoft Visual Studio solution (.sln)
runner)
Execute:
http://confluence.jetbrains.com/display/TCD8/Configuring+Build+Steps _If
all previous steps finished successfully (zero exit code)_
Solution file path: _src/NUnit-retry.sln_
Working directory: _same as checkout directory_
Visual Studio: _Microsoft Visual Studio 2012_
Targets: _Clean Rebuild_
Configuration: _Release_
Platform: _default_
Command line parameters: _none specified_
Run OctoPack: _not specified_
OctoPack package version: _not specified_
Step 3: _Tests_
Runner type: _Command Line_ (Simple command execution)
Execute:
http://confluence.jetbrains.com/display/TCD8/Configuring+Build+Steps _If
all previous steps finished successfully (zero exit code)_
Working directory: _src/NUnit-retry.Tests/bin/Release_
Custom script

Custom Script content:

copy NUnit-retry.dll "C:\Program Files (x86)\NUnit
2.6.3\bin\addins\NUnit-retry.dll"
"C:\Program Files (x86)\NUnit 2.6.3\bin\nunit-console.exe"
/xml:TestResult.xml NUnit-retry.Tests.dll
exit 0

working demo (login as guest) : http://teamcity.protorisk.com/

Let me know if you need further assistance

On Tue, Aug 18, 2015 at 2:28 PM, Martin Nilsson notifications@github.com
wrote:

> We are using Teamcity and run Selenium tests after a successful build. The
> tests are failing randomly and we have tried to fix them but no luck. We
> will now try with NUnit-retry.
> 
> Any guidance how to setup that step on TC? I can see that there is a
> project named TeamCity.NUnit.TestRunner.Proxy
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/slvnperron/NUnit-retry/issues/13.

## 

Sylvain Perron
Developer

Protorisk Ltd ¦ Mob: +1 (418) 440-7586 ¦ Web:  www.protorisk.com

AUTHORISED AND REGULATED BY THE FINANCIAL SERVICES AUTHORITY AS FIRM NO.
507471

Please click on the following link for our disclaimer and more information:
 disclaimer http://www.protorisk.com/disclaimer

**Comment by slvnperron** [comment]
Please do not use the proxy directly

**Comment by di97mni** [comment]
It worked. I used the TC launcher

```
%system.teamcity.dotnet.nunitlauncher% v4.0 x64 NUnit-2.6.3 /addin:NUnit-retry.dll TestAssembly.dll
```
